<?php

namespace LouvreBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
	public function countBilletsForDate($date)
	{
		$qb = $this->createQueryBuilder('c');
        $qb
            ->select('COUNT(c.billets)')
            ->where('o.date = :date')
            ->setParameter('date', $date);
	}
}
